9ff92334d61c1ac9c01db15f9eef4413bb137116a72d1ebfe808359d463c101a


kind: Secret
apiVersion: v1
metadata:
  name: gitlab-oauth-config
  namespace: devspaces 
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: gitlab
    che.eclipse.org/scm-server-endpoint: https://gitlab-gitlab.apps.cluster-9hbm4.9hbm4.sandbox2969.opentlc.com/
type: Opaque
stringData:
  id: 07ac167cf109330b647511aa91c801e32ae86c7d8742b711aeb71a1c07be92bf
  secret: 9ff92334d61c1ac9c01db15f9eef4413bb137116a72d1ebfe808359d463c101a


https://oauth-openshift.cluster-9hbm4.9hbm4.sandbox2969/oauth2callback/gitlab
