---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: johnwr
  description: johnwr group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: johnwr@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: johnwr
spec:
  profile:
    email: johnwr@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [johnwr]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: howard
  description: howard group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: howard@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: howard
spec:
  profile:
    email: howard@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [howard]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rubeus
  description: rubeus group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: rubeus@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rubeus
spec:
  profile:
    email: rubeus@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [rubeus]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: niteow2
  description: niteow2 group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: niteow2@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: niteow2
spec:
  profile:
    email: niteow2@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [niteow2]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: blackp
  description: blackp group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: blackp@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: blackp
spec:
  profile:
    email: blackp@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [blackp]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: moondra
  description: moondra group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: moondra@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: moondra
spec:
  profile:
    email: moondra@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [moondra]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: captainam
  description: captainam group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: captainam@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: captainam
spec:
  profile:
    email: captainam@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [captainam]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: saria
  description: saria group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: saria@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: saria
spec:
  profile:
    email: saria@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [saria]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: fi
  description: fi group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: fi@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: fi
spec:
  profile:
    email: fi@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [fi]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rachel
  description: rachel group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: rachel@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rachel
spec:
  profile:
    email: rachel@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [rachel]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: mercury
  description: mercury group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: mercury@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: mercury
spec:
  profile:
    email: mercury@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [mercury]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: thepun
  description: thepun group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: thepun@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: thepun
spec:
  profile:
    email: thepun@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [thepun]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: bishop
  description: bishop group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: bishop@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bishop
spec:
  profile:
    email: bishop@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [bishop]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: hogun
  description: hogun group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: hogun@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: hogun
spec:
  profile:
    email: hogun@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [hogun]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tempera
  description: tempera group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: tempera@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: tempera
spec:
  profile:
    email: tempera@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [tempera]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: humanb
  description: humanb group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: humanb@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: humanb
spec:
  profile:
    email: humanb@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [humanb]

